pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = 'PhoneLending'
include ':host', ':consumer'
project(':host').projectDir = file('apps/host/app')
project(':consumer').projectDir = file('apps/consumer/app')
